version: '3.9'

services:
  server:
    container_name: test_server
    build:
      context: ../../
      dockerfile: docker/images/server/Dockerfile
    image: swarm-server-tn:v0
    ports:
      - 2003:2003
    tty: true

  client1:
    container_name: test_client1
    build:
      context: ../../
      dockerfile: docker/images/client/Dockerfile
    image: swarm-client-tn:v0
    tty: true
    depends_on:
      - server

  client2:
    container_name: test_client2
    build:
      context: ../../
      dockerfile: docker/images/client/Dockerfile
    image: swarm-client-tn:v0
    tty: true
    depends_on:
      - server
